FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Install git and clone the software repository
RUN export DEBIAN_FRONTEND=noninteractive && \ 
    apt-get update && \
    apt-get install -y git build-essential curl software-properties-common  && \
    git clone -b inicia_plano https://github.com/ifsc-sj-2024-1-pji29008/client /app && \
    pip install --no-cache-dir -r requirements.txt && \
    rm -rf /var/lib/apt/lists/*

# Expose the port
EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

# Run the application
CMD ["streamlit", "run", "/app/app/home.py"]
