FROM alpine as cloner

# Install git and clone the software repository
RUN apk add --no-cache git && \
    git clone -b parametrizacao_plano https://github.com/ifsc-sj-2024-1-pji29008/software /app

# Build the definitive image
FROM python:3.11-alpine

# Copy the cloned repository to the image
COPY --from=cloner /app /app

# Install the required dependencies
RUN pip install -r /app/requirements.txt && \
    apk add --no-cache bash

# Set the working directory
WORKDIR /app

# Copy the entrypoint script
COPY entrypoint.sh /entrypoint.sh

# Copy the W1-simulator script
COPY w1_simulator /app/w1_simulator

# Expose the port
EXPOSE 5000

# Run the application
CMD ["/entrypoint.sh"]
